### ISSUE TITLE
How can I solve this "make" problem ?

### ISSUE THREAD

**Issue by ghost** [devsim/pisces#1]
Hello, I'm not so used to C programming.
When I followed the instruction ./pisces-master/INSTALL, at the 4th step,

To begin compiling start from the top level directory containing CMakeLists.txt:
1. mkdir cmake
2. cd cmake
3. cmake -DCMAKE_BUILD_TYPE=DEBUG ..
4. make 

I met the error messages shown at the bottom. How can I solve this problem ?

```
                                                          Kimihiro Ogawa
```

Warning: Obsolete: arithmetic IF statement at (1)
 In file /home/s037156b/MyC/DeviceSim/pisces-master/src/pisces/symbol.f:1509

```
     if(ixtop-j) 130,140,161                                        
                                                                   1
```

Warning: Obsolete: arithmetic IF statement at (1)
[ 98%] Building Fortran object src/pisces/CMakeFiles/pisces.dir/trefld.o
[ 98%] Building Fortran object src/pisces/CMakeFiles/pisces.dir/trfldmob.o
[ 99%] Building Fortran object src/pisces/CMakeFiles/pisces.dir/usrmob1.o
[ 99%] Building Fortran object src/pisces/CMakeFiles/pisces.dir/version.o
[100%] Building Fortran object src/pisces/CMakeFiles/pisces.dir/volume.o
Linking Fortran executable pisces
../plotcap/gplot/libplotcap_gplot.a(pg_erset.o): In function `pg_erset':
/home/s037156b/MyC/DeviceSim/pisces-master/src/plotcap/gplot/pg_erset.c:151: warning:`sys_errlist' is deprecated; use `strerror' or`strerror_r' instead
../sysf77lib/libsysf77lib.a(xmktmp_bsd.o): In function `xmktmp_':
/home/s037156b/MyC/DeviceSim/pisces-master/src/sysf77lib/xmktmp_bsd.c:61: warning: the use of`mktemp' is dangerous, better use `mkstemp'
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../lib64/libreadline.so: undefined reference to`PC'
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../lib64/libreadline.so: undefined reference to `tgetflag'
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../lib64/libreadline.so: undefined reference to`tgetent'
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../lib64/libreadline.so: undefined reference to `UP'
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../lib64/libreadline.so: undefined reference to`tputs'
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../lib64/libreadline.so: undefined reference to `tgoto'
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../lib64/libreadline.so: undefined reference to`tgetnum'
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../lib64/libreadline.so: undefined reference to `BC'
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../lib64/libreadline.so: undefined reference to`tgetstr'
collect2: ld returned 1 exit status
make[2]: **\* [src/pisces/pisces] Error 1
make[1]: **\* [src/pisces/CMakeFiles/pisces.dir/all] Error 2
make: **\* [all] Error 2

**Comment by tcaduser** [comment]
It looks like libreadline.so on your system needs access to the termcap library.  In src/pisces/CMakeLists.txt, you should put the proper library after "-lreadline".

According to this bug, https://bugzilla.redhat.com/show_bug.cgi?id=162023

 it might be "-ltermcap" or "-lncurses"  for your system.  Please let me know if this works.  Also, please let me know your operating system version.

**Comment by ghost** [comment]
Thanks, I could make it.
"-ltermcap" in the file src/pisces/CMakeLists.txt was effective.
I am using  Linux64 RHEL4 + Xeon

**Comment by ghost** [comment]
Sorry to bother you, but I met next problem.

$ ls -l
total 4340
drwxrwxrwx 2 s037156b xhg0284a    4096 May  8 08:40 .
drwxrwxrwx 8 s037156b xhg0284a    4096 May  7 16:29 ..
-rwxrwxrwx 1 s037156b xhg0284a  212947 May  7 16:34 bipmesh
-rw-rw-rw- 1 s037156b xhg0284a       5 May 30  2013 genkey.p2
-rwxrwxrwx 1 s037156b xhg0284a  238603 May  7 16:34 ig2image
-rwxrwxrwx 1 s037156b xhg0284a  183601 May  7 16:34 mosmesh
-rw-rw-rw- 1 s037156b xhg0284a   15620 May 30  2013 pisc.key
-rwxr-xr-x 1 s037156b xhg0284a     119 May 30  2013 pisces
-rwxrwxrwx 1 s037156b xhg0284a 3012669 May  8 08:40 pisces.bin
-rwxrwxrwx 1 s037156b xhg0284a  356662 May  7 16:34 skel
-rwxrwxrwx 1 s037156b xhg0284a  367721 May  7 16:34 tri

The target binary "pisces.bin" seems to be created, but

$ pisces -help
error: can't open `/home/s037156b/MyC/DeviceSim/pisces-master/bin/pisces.bin'

on the other hand, 

$ mosmesh -help
mosmesh: invalid option -- h
mosmesh: invalid option -- e
mosmesh: invalid option -- l
mosmesh: invalid option -- p

**Comment by tcaduser** [comment]
Do you see something like this:

```
~/git/pisces/cmake$ file ../bin/pisces.bin 
../bin/pisces.bin: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=0xcc3be4480ad5e6b6818090b6d2d4ed4f245e23d7, not stripped
```

In the install file, I show how to build the key file PISC2UKY and run an example.

**Comment by ghost** [comment]
Thank you for your reply, does this look working correct ?

$ ./pisces genkey.p2
C NOTE:
C  1. This is the f77 version of the gplot include file
C     and is supposed to be the same but for Fortran includes.
C  2. All underscores from the C form have been changed to 'x',
C     thus: G_DRAW has become GxDRAW
C  3. The macro functions have not been included.  These functions
C     have been implemented as fortran subroutines and are
C     available in the library.
C  4. This file was generated from `gplot.h' (the C form) by a
C     program, and as such is not so`pretty'. Sorry.

$ pisces nmos.p2
C NOTE:
C  1. This is the f77 version of the gplot include file
C     and is supposed to be the same but for Fortran includes.
C  2. All underscores from the C form have been changed to 'x',
C     thus: G_DRAW has become GxDRAW
C  3. The macro functions have not been included.  These functions
C     have been implemented as fortran subroutines and are
C     available in the library.
C  4. This file was generated from `gplot.h' (the C form) by a
C     program, and as such is not so`pretty'. Sorry.

$ pwd
/home/s037156b/MyC/DeviceSim/pisces-master/examples/pisces/test01

ls -l
total 24
drwxrwxrwx  2 s037156b xhg0284a 4096 May  8 12:55 .
drwxrwxrwx 15 s037156b xhg0284a 4096 May 30  2013 ..
-rw-rw-rw-  1 s037156b xhg0284a  826 May 30  2013 Makefile
-rw-rw-rw-  1 s037156b xhg0284a 1362 May 30  2013 README01
-rw-rw-rw-  1 s037156b xhg0284a  631 May 30  2013 mosIV.p2
-rw-rw-rw-  1 s037156b xhg0284a   34 May  8 12:55 nmos.out
-rw-rw-rw-  1 s037156b xhg0284a 1816 May 30  2013 nmos.p2

**Comment by tcaduser** [comment]
I am not sure what the problem is.  It looks like what you are running has something to do with plotcap.

This is what I see:

```
./pisces genkey.p2 



          ********* PISCES-II Device Modeling Program *********
                     (Version 9009-S.0523 SunOS 4.1)



                    Date and time = 10-May-15 18:32:21
```

Are you using Redhat 4? I can try the program on RH6 soon.

**Comment by ghost** [comment]
It is  Red Hat Enterprise Linux Server release 5.10 (Tikanga). 
Does this help ?

**Comment by tcaduser** [comment]
It might help.  I don't have a Redhat 5 machine immediately available.  Could you delete the cmake directory and go through the build process again?

**Comment by chihiro0019** [comment]
I tried to "cmake -DCMAKE_BUILD_TYPE=DEBUG .." and I found another error,

-------------------------------------------------------------------------------------------------------------------------------
cmake -DCMAKE_BUILD_TYPE=DEBUG ..
-- The Fortran compiler identification is GNU
-- The C compiler identification is GNU
-- Check for working Fortran compiler: /usr/bin/f95
-- Check for working Fortran compiler: /usr/bin/f95 -- works
-- Checking whether /usr/bin/f95 supports Fortran 90
-- Checking whether /usr/bin/f95 supports Fortran 90 -- yes
-- Check for working C compiler: /installtop/lx24-amd64/vendor/synopsys/HSPICE_J-2014.09/hspice/GNU/rhel/gcc-4.7.2/bin/gcc
-- Check for working C compiler: /installtop/lx24-amd64/vendor/synopsys/HSPICE_J-2014.09/hspice/GNU/rhel/gcc-4.7.2/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
CMake Error: Error in cmake code at
/home/s037156b/MyC/DeviceSim/pisces-master/src/pisces/CMakeLists.txt:56:
Parse error.  Expected a command name, got unquoted argument with text ".A".
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 2.6)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
------------------------------------------------------------------------------------------------------------------------------


and in the file /home/s037156b/MyC/DeviceSim/pisces-master/src/pisces/CMakeLists.txt:56:

the lilne 56 was what I modified according to your previous advice as shown below


-------------------------------------------------------------------------------------------------------------------------------
# Kim O.  2015.05.08
# TARGET_LINK_LIBRARIES(pisces genii3 sysf77lib plotcap_f77links plotcap_gplot plotcap_high2 edline -lreadline)
 
TARGET_LINK_LIBRARIES(pisces genii3 sysf77lib plotcap_f77links plotcap_gplot plotcap_high2 edline -lreadline -ltermcap)
-----------------------------------------------------------------------------------------------------------------------------

**Comment by ghost** [comment]
I tried to cmake again, and  there is an error.

---

$ cmake -DCMAKE_BUILD_TYPE=DEBUG ..
-- The Fortran compiler identification is GNU
-- The C compiler identification is GNU
-- Check for working Fortran compiler: /usr/bin/f95
-- Check for working Fortran compiler: /usr/bin/f95 -- works
-- Checking whether /usr/bin/f95 supports Fortran 90
-- Checking whether /usr/bin/f95 supports Fortran 90 -- yes
-- Check for working C compiler: /installtop/lx24-amd64/vendor/synopsys/HSPICE_J-2014.09/hspice/GNU/rhel/gcc-4.7.2/bin/gcc
-- Check for working C compiler: /installtop/lx24-amd64/vendor/synopsys/HSPICE_J-2014.09/hspice/GNU/rhel/gcc-4.7.2/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
CMake Error: Error in cmake code at
/home/s037156b/MyC/DeviceSim/pisces-master/src/pisces/CMakeLists.txt:56:
Parse error.  Expected a command name, got unquoted argument with text ".A".
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

```
cmake_minimum_required(VERSION 2.6)
```

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

  -- Configuring incomplete, errors occurred!

---

This error is related to the modification I made according to your advice.
/home/s037156b/MyC/DeviceSim/pisces-master/src/pisces/CMakeLists.txt:56:

anything wrong ?

---

 # Kim O.  2015.05.08
 # TARGET_LINK_LIBRARIES(pisces genii3 sysf77lib plotcap_f77links plotcap_gplot plotcap_high2 edline -lreadline)
 
  TARGET_LINK_LIBRARIES(pisces genii3 sysf77lib plotcap_f77links plotcap_gplot plotcap_high2 edline -lreadline -ltermcap)

---

**Comment by ghost** [comment]
The situation became a little better, now I got an error

$ pwd
/home/s037156b/MyC/DeviceSim/pisces-master/cmake
$  cmake -DCMAKE_BUILD_TYPE=DEBUG ..
CMake Error: Error in cmake code at
/home/s037156b/MyC/DeviceSim/pisces-master/src/pisces/CMakeLists.txt:60:
Parse error.  Expected a command name, got unquoted argument with text ".A".
-- Configuring incomplete, errors occurred!

1 CMakeLists.txt had some different text code on our machine, I changed it according to
   EMACS warning.
2 I added 
   cmake_minimum_required(VERSION 2.6)
   at the 1'st line of CMakeLists.txt

Then how can I solve the problem shown above ?
Here are lines around /home/s037156b/MyC/DeviceSim/pisces-master/src/pisces/CMakeLists.txt:60

###TARGET_LINK_LIBRARIES(pisces genii3 sysf77lib plotcap_f77links plotcap_gplot plotcap_high2 edline -lreadline)
 
TARGET_LINK_LIBRARIES(pisces genii3 sysf77lib plotcap_f77links plotcap_gplot plotcap_high2 edline -lreadline -ltermcap)

**Comment by tcaduser** [comment]
CMAKE may only be able to handle ASCII characters.  Please be careful to make sure to only use the ASCII code characters 1-128.

**Comment by ghost** [comment]
I think this time the executable seems to be made.

$ make

....
....
[ 98%] Building Fortran object src/pisces/CMakeFiles/pisces.dir/trefld.f.o
[ 98%] Building Fortran object src/pisces/CMakeFiles/pisces.dir/trfldmob.f.o
[ 99%] Building Fortran object src/pisces/CMakeFiles/pisces.dir/usrmob1.f.o
[ 99%] Building Fortran object src/pisces/CMakeFiles/pisces.dir/version.f.o
[100%] Building Fortran object src/pisces/CMakeFiles/pisces.dir/volume.f.o
Linking Fortran executable pisces
../plotcap/gplot/libplotcap_gplot.a(pg_erset.c.o): In function `pg_erset':
/home/s037156b/MyC/DeviceSim/pisces-master/src/plotcap/gplot/pg_erset.c:151: warning:`sys_errlist' is deprecated; use `strerror' or`strerror_r' instead
../sysf77lib/libsysf77lib.a(xmktmp_bsd.c.o): In function `xmktmp_':
/home/s037156b/MyC/DeviceSim/pisces-master/src/sysf77lib/xmktmp_bsd.c:61: warning: the use of`mktemp' is dangerous, better use `mkstemp'
[100%] Built target pisces

However, licensing doesn't seem to be completed.

$ ./pisces genkey.p2 
C NOTE:
C  1. This is the f77 version of the gplot include file
C     and is supposed to be the same but for Fortran includes.
C  2. All underscores from the C form have been changed to 'x',
C     thus: G_DRAW has become GxDRAW
C  3. The macro functions have not been included.  These functions
C     have been implemented as fortran subroutines and are
C     available in the library.
C  4. This file was generated from `gplot.h' (the C form) by a
C     program, and as such is not so`pretty'. Sorry.

**Comment by tcaduser** [comment]
Hi,

It is difficult for me to help you since I don't have access to a Redhat 5
machine.  Do you have access to a more recent linux?

Regards,

Juan

**Comment by ghost** [comment]
Thank you for your kind support.
I still have some problems, but I give up to continue.
I heard that the other guys in my company have already installed this.
They are using local machine on which they can be the root unlike my case.
It might be the largest problem for me. I apologize it and thank you for your
very kind support, I appreciate you.
